language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
env:
  - PYTEST=2.6.4
  - PYTEST=2.7.2
install:
  - travis_retry pip install -q pytest==$PYTEST
  - travis_retry pip install -q -e .
script:
  - py.test
