language: python
sudo: false
cache: pip
python:
  - 3.5
env:
  - TOXENV=py27-pytest29-supported-xdist
  - TOXENV=py27-pytest29-unsupported-xdist
  - TOXENV=py34-pytest29-supported-xdist
  - TOXENV=py35-pytest29-supported-xdist
  - TOXENV=py35-pytest29-unsupported-xdist
  - TOXENV=pypy-pytest29-supported-xdist
install: pip install -U tox
script:
  - tox
