language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
env:
  - PYTEST=2.3.4
  - PYTEST=2.2.4
  - PYTEST=2.1.3
  - PYTEST=2.0.3
install:
  - pip install -q pytest==$PYTEST --use-mirrors
  - pip install -q -e . --use-mirrors
script:
  - py.test
