dist: xenial
language: python
cache: false
python:
  - 3.7
matrix:
  include:
    - env: TOXENV=py27-pytest36-supported-xdist
      python: 2.7
    - env: TOXENV=py27-pytest37-unsupported-xdist
      python: 2.7

    - env: TOXENV=py34-pytest38-supported-xdist
      python: 3.4
    - env: TOXENV=py35-pytest39-supported-xdist
      python: 3.5
    - env: TOXENV=py36-pytest40-supported-xdist
      python: 3.6

    - env: TOXENV=py37-pytest41-supported-xdist
    - env: TOXENV=py37-pytest42-supported-xdist
    - env: TOXENV=py37-pytest42-unsupported-xdist-rerunfailures

    - env: TOXENV=qa
install: pip install -U tox
script:
  - tox
