language: python
sudo: false
cache: pip
python:
  - 3.6
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5 pypy
env:
  - TOXENV=py27-pytest30-supported-xdist
  - TOXENV=py27-pytest30-unsupported-xdist
  - TOXENV=py34-pytest30-supported-xdist
  - TOXENV=py35-pytest30-supported-xdist
  - TOXENV=py35-pytest30-unsupported-xdist
  - TOXENV=pypy-pytest30-supported-xdist
install: pip install -U tox
script:
  - tox
