language: python
sudo: false
cache: pip
python:
  - 3.5
env:
  - TOXENV=py26-pytest26-supported-xdist
  - TOXENV=py26-pytest27-supported-xdist
  - TOXENV=py26-pytest28-supported-xdist
  - TOXENV=py27-pytest26-supported-xdist
  - TOXENV=py27-pytest27-supported-xdist
  - TOXENV=py27-pytest28-supported-xdist
  - TOXENV=py27-pytest26-unsupported-xdist
  - TOXENV=py27-pytest27-unsupported-xdist
  - TOXENV=py27-pytest28-unsupported-xdist
  - TOXENV=py33-pytest26-supported-xdist
  - TOXENV=py33-pytest27-supported-xdist
  - TOXENV=py33-pytest28-supported-xdist
  - TOXENV=py34-pytest26-supported-xdist
  - TOXENV=py34-pytest27-supported-xdist
  - TOXENV=py34-pytest28-supported-xdist
  - TOXENV=py35-pytest26-supported-xdist
  - TOXENV=py35-pytest27-supported-xdist
  - TOXENV=py35-pytest28-supported-xdist
  - TOXENV=py35-pytest26-unsupported-xdist
  - TOXENV=py35-pytest27-unsupported-xdist
  - TOXENV=py35-pytest28-unsupported-xdist
  - TOXENV=pypy-pytest26-supported-xdist
  - TOXENV=pypy-pytest27-supported-xdist
  - TOXENV=pypy-pytest28-supported-xdist
install: pip install -U tox
script:
  - tox
